{% set name = "hart-protocol" %}
{% set version = "2023.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hart-protocol-{{ version }}.tar.gz
  sha256: 972090f15f6449dba018f02e61c4ea5400b4b2b63de5e1c2e60ddedb8f0209af

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - flit-core
  run:
    - python >=3.7

test:
  imports:
    - hart_protocol
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/yaq-project/hart-protocol
  summary: A sans-io python implementation of the Highway Addressable Remote Transducer Protocol.
  dev_url: https://github.com/yaq-project/hart-protocol
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - untzag
