{% set name = "hart-protocol" %}
{% set version = "2023.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 1c97810c91cabb18947f7a0bb25749dce0984645c3647d8f294d2e2abc8f9c80

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - flit-core
  run:
    - python >=3.7

test:
  imports:
    - hart_protocol
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/yaq-project/hart-protocol
  summary: A sans-io python implementation of the Highway Addressable Remote Transducer Protocol.
  dev_url: https://github.com/yaq-project/hart-protocol
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - untzag
